---
- name: Install the Docker in CentOS
  hosts: all
  tasks:
   - name: Install the YUM Utilis
     yum:
      name: "{{ item }}"
      state: present
     with_items:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
   - name: Add Docker Repo
     get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo
   - name: Download the containerd
     get_url:
      url: https://download.docker.com/linux/centos/7/x86_64/test/Packages/containerd.io-1.4.3-3.1.el7.x86_64.rpm
      dest: /docker/
      mode: 0775
   - name: Install the Contianerd
     command: sudo yum install -y /docker/containerd.io-1.4.3-3.1.el7.x86_64.rpm
   - name: Install the Docker
     package:
      name: docker-ce
      state: latest
     become: yes
   - name: Create the User
     user:
      name: " {{ item }}"
      groups: docker
      state: present
     with_items:
      - srikanth
   - name: Start the Docker Service
     service:
       name: docker
       state: restarted
       enabled: yes
     become: yes